server:
    port: 7070

spring:
    application:
        name: storage-v1-0
  

logging:
    file: storage-service/logs/skeleton.log
    

storage:
    repositories:
        - name: g1
          type: GOOGLE
          rootDirectory: 
          clientSecrets: /client_secret.json
        - name: g2
          type: GOOGLE
          rootDirectory: 
          clientSecrets: /client_secret2.json
        - name: l1
          type: FS
          rootDirectory: d:/tmp
        - name: l2
          type: FS
          rootDirectory: d:/temp
        - name: testlpe
          type: FS
          rootDirectory: D:\home\eclipse_workspace\es_head\icons\icon16  



#remove this block in cloud environment    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false