server:
    port: 8000
   

spring:
    application:
        name: storage-v1-0
  

logging:
    file: storage-service/logs/skeleton.log
    

  
storage:
    repositories:
        - name: g1
          type: GOOGLE
          rootDirectory: 
          clientSecrets: /client_secret.json
        - name: g2
          type: GOOGLE
          rootDirectory: 
          clientSecrets: /client_secret2.json
        - name: l1
          type: FS
          rootDirectory: d:/tmp
        - name: l2
          type: FS
          rootDirectory: d:/temp
        - name: testlpe
          type: FS
          rootDirectory: D:\home\eclipse_workspace\es_head\icons\icon16
        - name: od1
          type: ONEDRIVE
          clientSecrets: /microsoft_secret.json
    

#remove this block in cloud environment    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  
#security:
#   oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#       user-info-uri: https://graph.facebook.com/me

#storage-v1-0:
#    ribbon:
#        eureka:
#            enabled: false
#        listOfServers: localhost:7070
#        ServerListRefreshInterval: 15000

#security:
#   oauth2:
#    client:
#      clientId: e4880281-7bc6-48c4-9a95-4b0ee9fb0cba
#      clientSecret: MyGnyPdRuQe12RJSFRNobTe
#      accessTokenUri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#      userAuthorizationUri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#      tokenName: access_token
#      authenticationScheme: header
#      clientAuthenticationScheme: form
#      scope: files.readwrite offline_access 
#    resource:
#       user-info-uri: https://graph.microsoft.com/v1.0/me

